services:
  postgres:
    image: postgres:15
    container_name: soa_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serviceoriented
    ports:
      - "5432:5432"
    volumes:
      - soa_pg_data:/var/lib/postgresql/data

  web11:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: soa_web11
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/serviceoriented
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  web12:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: soa_web12
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/serviceoriented
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy1
    container_name: soa_haproxy
    restart: always
    ports:
      - "34566:8443"

volumes:
  soa_pg_data:
