services:
   mongo:
    image: mongo:latest
    container_name: soa_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: serviceoriented
    ports:
      - "27017:27017"
    volumes:
      - soa_mongo-data:/data/db
      - soa_mongo-config:/data/configdb

volumes:
  soa_mongo-data:
    driver: local
  soa_mongo-config:
    driver: local
