server:
  port: 8081

web1:
  service:
    url: ${WEB1_SERVICE_URL:https://localhost:34566}

spring:
  application:
    name: mule-esb

cxf:
  path: /ws
  servlet:
    init:
      service-list-path: /services
  
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.apache.cxf: INFO
    org.apache.camel: INFO
    ru.ifmo.muleesb: DEBUG

camel:
  springboot:
    name: CityManagementESB
  component:
    cxf:
      allow-streaming: false
